### ISSUE TITLE
Print and Answer key functions not working

### ISSUE THREAD

**Issue by juliastad** [toebes/ciphers#123]
I click to print or view the test or the answer key, and it only shows me the menu.

**Comment by toebes** [comment]
I would be more than happy to fix it if you could provide an example.

**Comment by InvisibleIncubus** [comment]
I am having the same issue. Click on Test Manager and there's the usual list of tests, but when I click on "edit" to continue making the test, it goes to this: 
![image](https://user-images.githubusercontent.com/46539793/66325450-83a00280-e8e4-11e9-9237-7d9783382619.png)
Same thing happens if I click on "Test Packet" or any of the other options. I am using Firefox.

**Comment by InvisibleIncubus** [comment]
Seems to work fine on Chrome, but all my stuff is saved on Firefox.

**Comment by RanTheLab** [comment]
This usually happens when there is an unexpected error.  The error can be revealed by going to the Firefox menu, select "Web Developer", then "Web Console"... please provide the information you find there in this issue.

**Comment by InvisibleIncubus** [comment]
It just shows me my extensions. 
![image](https://user-images.githubusercontent.com/46539793/66326332-01b0d900-e8e6-11e9-8c60-01583132794b.png)

**Comment by InvisibleIncubus** [comment]
Yes, that's what I did.

**Comment by RanTheLab** [comment]
OK I see now.  Can you leave that web console open and recreate the issue?

**Comment by toebes** [comment]
We have fixed several issues in this area.  If this is still happening, can you please let us know.

**Comment by toebes** [comment]
We've not seen this issue occur since some work in this area.  If you encounter it in the future, please open a new issue and we will fix it.
