### ISSUE TITLE
Year

### ISSUE THREAD

**Issue by nature812** [toebes/ciphers#137]
Hello

 In the heading default year is 2019,, I am setting paper for invitational in 2020. How can I not have 2019?
Thanks
V

**Comment by RanTheLab** [comment]
There is currently a fudge value of 6 days for the year...within 6 days of the end of the year, the year is incremented.  Instead of guessing some other value or adding complexity to the user experience with buttons and the like, we've decided to remove the year altogether.  The test year can always be put in the title.

**Comment by nature812** [comment]
In the test paper there is still default 2019
Thanks

**Comment by RanTheLab** [comment]
> In the test paper there is still default 2019
> Thanks

The web site was just updated a few minutes ago.

**Comment by nature812** [comment]
Thanks
