### ISSUE TITLE
double letters - refresh does not work

### ISSUE THREAD

**Issue by MaMaNina** [toebes/ciphers#312]
K1 Aristocrat is having double letters in the plain text when solving for the keyword instead of the decoded plain text. Users on different computers and different networks unable to see the what the other users are entering in the plain text (but they can see the notes and keyword). When each user tried to refresh (per instructions) to reset the network connection, it does not fix it. All that refresh does is wipe out every letter of progress each user has made on that particular cipher. This is the second text I have made that this has happened to.

**Comment by toebes** [comment]
This has been fixed.  We got a reproducible case and were able to push out a fix.  Note however that you will have to regenerate the interactive test because the problem is in the test model that was generated.

1. Click on Test Manager and then the Published button to see the tests you have on the server (https://toebes.com/codebusters/TestPublished.html)
2. Find the problem test and then click on the delete button for it
3. Click on the Local button to see your local test
4. Click on Interactive Test to generate the test on the server.
