### ISSUE TITLE
Cryptarithm format

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#363]
Guys, I think the current "Cryptarithm Encrypt" page is using the wrong format for specifying a cryptarithm problem, and also the wrong format for the students to specify the answer. The current interface focuses on setting a problem in which the letters in the problem statement form words. That is a very hard problem and that means that finding a problem with that format doesn't leave the setter with flexibility to make sure that there is a reasonable path to finding the solution.

Instead, I would argue that we should be taking the Science Olympiad rules for this event more seriously: "**3.e.vi. Cryptarithms – determining mapping values to letters in mathematical equations and extracting the word or words used for mapping**". I read this as meaning that, as in the ACA, the answer to a cryptarithm problem should always be the letters arranged in digit order to spell out one or more words. 

I would like the interface to be the following: In the "Problem" textbox, the setter specifies a math problem using numbers (i.e., **digits**). Then in the "Solution" textbox the setter specifies 10 distinct letters. There should also be a set of radio controls (or a dropdown) to indicate the digit order for the answer, either 0-9, 9-0, 1-0, or 0-1.  Then the presented problem would give both 

1. the math problem as it currently does, but with each digit in the "Problem" translated to the corresponding letter from the "Solution", and
2. a space for the answer with the digits given in the correct order, with space to fill in the correct letter above each digit.

The beauty of this interface is that it de-couples the choice of the keyword "Solution" from the choice of the math "Problem". That means that the setter can go over possible math problems looking for one that has a reasonable path to solution, and only worry about the keyword later. We should encourage everyone to think of the problem as an encryption of the keyword -- and that it is therefore expected to look like gibberish. The decryption is found by solving the math problem.  

In any case, I think it is important to follow the rules set down by Science Olympiad stating that the answer is the 10-letter keyword.

I realize that this is a big change. An early downpayment on a change like this would be to include digits 0-9 for the students to write in the corresponding letters, with this block labeled as the "Answer". That would at least get setters, coaches, and students used to the idea that this is the correct format for a solution.

Oh, and the page should be called "Cryptarithm Decrypt" shouldn't it? Because the students are being asked to decrypt the cryptarithm.

**Comment by toebes** [comment]
Thank you for the feedback!  Hopefully the updated version of the Cryptarithm page should address the issues.  

One of the things to be aware of with how the rules were written for Codebusters is that the answer doesn't have to be exactly 10 digits/letters or even use them all.  This was done on purpose to make it both easier on the test writer and for the students in order to ensure that they stand a chance of solving the Cryptarithm in the 10 minute target time.  You should also notice the 10x10 work box to help the students track digit possibilities more easily.

One of the hardest part of writing this generator was creating code to ensure that any formula that is put in has exactly one solution. 

We have also posted some sample [Christmas_2022_Cryptarithms](https://toebes.com/codebusters/TestManage.html?importURL=https://toebes.com/codebusters/Samples/Christmas_2022_Cryptarithms.json) which should give an idea of what is intended.

We will also be posting soon a guide to help test writers create Cryptarithms.

Let us know what you think.
