### ISSUE TITLE
Printing guidelines?

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#470]
Is there a national guideline on whether it is best practice to print this exam single-sided or double-sided?  In my state and in a remote tournament we have participated in in another state, it is suggested to print it single-sided. Would it be helpful to add this to the Exam Preparation portion of the Answer Key where it also suggests using manila folders and that they need not be stapled?

I know the first time I gave this one, I could not find printing guidelines anywhere. Printed 60 copies of the whole thing double-sided before learning otherwise and had to reprint it. Of course, being consistent within a competition is primary, but if there's a suggested guidance it would be helpful to have it written somewhere.

**Comment by toebes** [comment]
Funny you should ask.  We were just talking about printing this morning.

The basic guidelines for what we do in NC to optimize paper is:
Take the generated test and drop out the blank page after the score page and the two pages for the resource sheet.  Then print those pages all single sided.  Print three copies of the resource page double sided.  Take the first page of the test and paperclip it to a folder, then put the three double sided resource sheets on top of the remainder of the test and put that in the folder.  In this way you don't even need scrap paper because they can use the back of the test for any scrap. 

With that being said, we are looking to add an option to the test printing code to enable doing that easier.

**Comment by Agilus** [comment]
This is fantastic, thanks so much! NC is very generous with the resource sheet - my students will be happy with the new guidance! :)
