### ISSUE TITLE
The Aristocrat, Patristocrat, and Xenocrypt should not show the special bonus check box

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#475]
Since you can't mark them as a special bonus, the checkbox should not be shown
<img width="735" alt="image" src="https://github.com/toebes/ciphers/assets/12609253/b35785b7-8f8b-4325-828d-e79f65ab2c3d">

**Comment by toebes** [comment]
Fixed with https://github.com/toebes/ciphers/commit/e30fcb5c1c5f0ccd631c009354c6e7d4e7d7d25f

**Comment by Agilus** [comment]
If I use the test builder to build a test and later change the question type of a bonus question to Aristocrat, because the checkbox is gone, I am no longer able to remove the checkmark. This makes my test throw an error telling me that an Aristocrat cannot be a bonus question, but there's no way to correct it aside from deleting the question entirely. It's probably on me for taking the easy way out and just changing the question type, but maybe if I change a bonus question to an Aristocrat it should automatically "uncheck" the box that no longer shows?

**Comment by toebes** [comment]
Fixed - minor oversight on my side with the code.
