### ISSUE TITLE
add polybius keys with repeating characters

### ISSUE THREAD

**Issue by jenniferdevlin** [toebes/ciphers#481]
Using a polybius key with some repeating characters increases the difficulty of solving a Nihilist Cipher.  Could this option be added once you click the Suggest Polybius Key button?

**Comment by toebes** [comment]
There is now a third row with the words (up to 14 characters long I might add) that include duplicated letters.
<img width="671" alt="image" src="https://github.com/toebes/ciphers/assets/12609253/e87f8d78-2dcd-46d5-b660-f907ccd2582a">

**Comment by Agilus** [comment]
I am curious about the word lists that are used for generating the keywords. I can't find any evidence that "ACCESSABLE" is, in fact, a word. Some of the words seem to be proper names. And some of the words are words but perhaps ones that are not especially suitable for the task (e.g., DOUCHEBAG).

**Comment by toebes** [comment]
Alas, they come from a Corpus of words gathered by Google (and a few other sources) based on an analysis of millions of books.  As I find bad words, I've been deleting them from the list, but there are over 470,574 words in the list and unfortunately misspelled words and inappropriate words get in there.  Believe it or not, some of the misspelled words like ACCESSABLE occur in both printed material and unfortunately on websites which gets it added to the list.  

The entire list can be found at https://github.com/toebes/ciphers/blob/master/Languages/en.txt and we would certainly welcome anyone who wishes to help filter down the list.  

To reduce the likelihood of some of these deliberately misspelled words, we have reduced the list of choice words to only the first half of the list (which helps, but isn't perfect).  

We are definitely open to suggestions for how to curate the list of words (or even a better source of word lists).  

This particular one came from a combination of the ACA English word lists and 

Other sources we have looked at include:

- https://websites.umich.edu/~jlawler/wordlist
- https://github.com/hackerb9/gwordlist 
- https://github.com/dwyl/english-words

What is absolutely astonishing is that none of these sources provide any level of consistency...

**Comment by Agilus** [comment]
How can I help? I would totally read four hundred thousand words for you guys. :) 

I think it might be helpful to think about what characteristics you want your keywords to have. Obviously, likely nonwords (GLVE, APRLL, KNOWYOU, POUNDLNG) are undesirable. You could probably dump those out just by cross-checking the list you have with a known dictionary (or if you want to be really conservative, trying to figure out what characteristics some of these words have: five consonants in a row? four consonants in a row of which none of them are S? etc.) Do you want the words to be "clean" (for example, f*ckhead is on the list, and there is at least one motherf* variety)? What about proper names? What about words that no one will know (trimeresurus, xeronate)? (I realize claiming that there are words that "no one will know" is a bold statement in Science Olympiad!)

I would offer that once a word becomes sufficiently uncommon, it loses its utility as a keyword for the purposes of this competition. It would be hard for students even who are native speakers of English to find, to recover, and to use such unrecognizable words to solve their Xenocrypts or Patristocrats. So you may not really want a list of all words. You may instead want a clean word list of the most common X# of words. If the word list you have is over 400,000 words, there may only be 100,000 or fewer that would really be suitable keywords.

Not sure if this is helpful because I'm not a developer by trade so I don't understand the technical pieces, but Merriam Webster apparently has a list of student friendly vocabulary. It's over 100,000 words and is available here - I'm also not able to look inside but thought I'd toss a link in here. https://www.dictionaryapi.com/

If you play Squaredle, which I would recommend to anyone, the developer talks about how he curates his word lists here (based off of the Scrabble word list and then using word frequencies and personal experience to judge which words are required in his game and which are "bonus words"):
https://squaredle.app/faqs.html#What-is-a-valid-word
and
https://blog.squaredle.app/making-of-squaredle

Seriously, though, if there's some way I can help, let me know.
