### ISSUE TITLE
K2 Aristocrat with Keyword Replacement Table Incorrect in Answers and Solutions

### ISSUE THREAD

**Issue by kmwoodb1973** [toebes/ciphers#486]
I'm generating practice tests for my Codebusters and noticed that the keyword replacement tables in the solutions are not correct for K2 aristocrats with keywords. Here, the keyword of "STUDYING" is not correct to the cipher. It ends up being KLEMNIOG
![Screenshot 2024-02-06 121046](https://github.com/toebes/ciphers/assets/159180953/0779abb7-2ceb-431d-ba69-c74d1bba8fc9)

**Comment by toebes** [comment]
hi @kmwoodb1973 ,
  I've tried to reproduce the problem here and my view of the test and the answers/solutions appears to be what I expect (and it matches what you have in the pasted problem).  If you could point out where you are seeing the KLEMNIOG as an issue?  I should point out that those letters are what the second level lookup of the letters BCDEFGHI map to, but that is how a K2 works.
  
<img width="802" alt="image" src="https://github.com/toebes/ciphers/assets/12609253/819d9478-6ad1-4271-b5b3-2a614c4268a2">
<img width="1627" alt="image" src="https://github.com/toebes/ciphers/assets/12609253/542f2231-5906-4719-91a5-8210b6a89e25">

Feel free to save the sample test and send it to [codebusters@toebes.com](mailto:codebusters@toebes.com) if you want to keep the remainder of the questions out of the public spotlight.

**Comment by kmwoodb1973** [comment]
When I solve the cipher, I get solution (worked out by hand) vs. the automated solution key... Possible I don't understand how the solutions for K2 work, though all other cipher solutions have been very straight forward. 
![Screenshot 2024-02-06 224519](https://github.com/toebes/ciphers/assets/159180953/b9f45a69-6a36-4693-ba18-fad67200ad4c)

**Comment by kmwoodb1973** [comment]
I see what I'm doing wrong now. I'm flipping the plaintext and ciphertext in my table, essentially. When I list the ciphertext letter above the plaintext letter it aligns to, then the table is accurate. User error strikes again. Thanks for the help!

**Comment by toebes** [comment]
We are glad you got things working!  Have a wonderful day.
