### ISSUE TITLE
Feature request: Baconian display options

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#489]
I've had some trouble getting my Baconian letter-for-letter/sequences to appear how I wish, both if I make my own and if I use the new tool that selects options for me. 

Here are a few examples:

In these first two cases, I think it's true that the preview looks fine and the problem only happens when I send the PDF to be printed, and only on the global copiers at our school. (I think we print using PaperCut Mobility Print on ChromeOS). I've learned in writing this post that the problem doesn't occur on my printer at home. It might be beyond the scope of your work, but there's no way to tell in advance whether my Baconian will come out of the printer as I expect it to, or not. 

Using the tool - A: m̂aĝiĉ B: mǎgǐc
These look fine in the tool and in the PDF test packet preview, but when I send it to the printer, some of the carats shift and connect to each other so they look like tildes, and it is difficult to tell which letter is associated with which carat.

My own: A: ☠☢☒  B:♻✆☑ 
These look fine in the tool (all black and white), they look fine in the preview below the tool, apparently they look fine in the PDF Test packet preview, but, a bunch of them do not print when I send it to the printer. It is not especially consistent which ones do not print - for example, just a smattering of them printed in the first three lines, and then I think in the last two lines of my Baconian, they all printed.

I wonder if even on the school printers, the problems with these two would resolve with a bit more spacing between the characters? That's the feature request.

And on the following two, I wish I could have an option to make the characters appear larger (I edited the page source to get the desired size when I printed my Northview test). 
A: ⍁⍂⎅⌹⍇⍈  B: ⍃⍄⌺⌸⌼
and
A: 🁫🁴🂄🂎🂉🁽  B: 🁷🂃🁬🁾🂈🂑

**Comment by toebes** [comment]
Basically what is happening is that the School printer is not interpreting the PDF with the correct font.  There is an option when you open up the PDF with Adobe Acrobat to force the font to be embedded, but I am not sure that the school printer is respecting it.  In this case we are using a web font for the A: m̂aĝiĉ B: mǎgǐc characters and apparently the font is not being embedded correctly.  A similar thing is happening with the emoji's A: ☠☢☒ B:♻✆☑, the font that the school printer is using is not matching what is on the screen.  It is possible that an option with Acrobat may be able to override it.

With that being said, I've found a way to have the code generate an image instead of fonts for the characters (https://www.codepel.com/vanilla-javascript/generate-image-from-text-javascript/) and will look at adding two options to the baconian generator
  1) A check box to tell the tool to generate an image instead of fonts to work around the printer problems
  2) Either a check box or a size override % (default 100%) to increate the size of the characters.

**Comment by Agilus** [comment]
You're the best, thank you!

**Comment by toebes** [comment]
@Agilus It is now pushed into production.  Let us know what you think.

**Comment by Agilus** [comment]
Circling back on this one, it's fantastic. Baconians with emojis were very popular at practice! I also scaled up my icons and that was wonderful, too. Thank you!
