### ISSUE TITLE
Complete Columnar solver ends too early

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#495]
From the Test Builder:

Quote: Police have arrested the World tongue-twister Champion. I imagine he'll be given a tough sentence.
Columns: 9
Ordering: 297856725
Crib: POLICE

It does not seem to pursue the option where the entire crib is contained in one row. It begins with the more difficult split-crib option, tries several paths, throws them all out, decides the crib must be contained in one row, and then gives up (it was so close!). It does throw a warning at me that my crib is inadequate to come to a solution, but I don't think that's really the case.

**Comment by RanTheLab** [comment]
Well, it turns out that IS the reason!  As stated in the rules "...given a crib which is no shorter than one less than the number of columns used."  If the crib is too short, then the number of combinations that students need to work through gets big and becomes 'busy work'.  In your example, that number is 24 combinations...the code only tolerates less than 11 combinations.  I have added additional output to make this clearer, in addition to the warning.
![image](https://github.com/toebes/ciphers/assets/7691169/90e0f118-4cf7-48e7-b1ca-74464c33f007)

**Comment by Agilus** [comment]
Hmm. But right as it arrived at the correct solution, it quit. 

I'm understanding where you're coming from, but the rules for the State/Nationals say: Cryptanalysis of the Complete Columnar Transposition Cipher - Decrypting ciphertext encoded in 11 columns or less given a crib which is no shorter than three less than the number of columns used.

That actually brings me to one that I hadn't gotten around to inputting yet, which is that if I make a State/National exam, it throws an error if my crib is any shorter than one fewer than the number of columns used. 

It sounds like you are making a suggestion that this one might be too difficult, which is something I've advocated for on other ciphers so I don't dislike it. But I think if I give this to my students, they won't have any problem with it given that they will start by looking for POLICE in one row and HAVE becomes readily apparent since we are cipher-initial.

**Comment by Agilus** [comment]
Update: two students solved this individually in 7:10 and 7:42.
