### ISSUE TITLE
K2 Suggest Keyword not fully functioning

### ISSUE THREAD

**Issue by jenniferdevlin** [toebes/ciphers#516]
While editing an Aristrocrat question on a test, I clicked on the "Suggest Keyword" button for a K2 alphabet.  I am only seeing blue "Use Offset +1" buttons after suggested words.  I am used to seeing both blue and yellow buttons (as described in the NOTE in the screen shot below) and used to seeing varying offset choices (not just +1).  This is happening for both "Decode" and "Keyword/Key Phrase".
<img width="897" alt="Screen Shot 2024-04-20 at 1 59 35 PM" src="https://github.com/toebes/ciphers/assets/125524378/a6cb6929-aaf8-419c-9f4c-b2f9fb3d655b">

**Comment by toebes** [comment]
I noticed it too so need to figure out where the yellow went...

**Comment by Agilus** [comment]
This was working fine for me today?

**Comment by jenniferdevlin** [comment]
Today for me the K2 keyword suggestion button is only showing yellow
buttons (and no blue buttons).
https://app.screencastify.com/v3/watch/SrOKUJiFssIuZJ9SGHSN

thank you for your time on this wonderful site!!

Jennifer Devlin (she/her/hers)
***@***.***
Pennsylvania Science Olympiad
http://www.PASciOly.org <http://www.pascioly.org/>

**Comment by Agilus** [comment]
I don't work here, but I also appreciate your contributions to this tool :) 
I think the issue you experienced today is due to your choice of plain text. I checked out your screencastify and recreated what you were able to make and had the same issue you had, but if you add a second sentence to it like "Jennifer has done a lovely job using screencastify to demonstrate the issue." (which is the one I tried) and try to Suggest Keyword, you will get almost all blue ones because you then will have coverage of enough unique letters of the alphabet to enable a more robust keyword generation. 

Happy to let the final word lie with the powers that be, but I hope until they get back to you, this helps you get back to ciphering :)

**Comment by toebes** [comment]
After spending some time looking at it, I think that @Agilus has figured it out.  I looked at the code and the cases where we only get blue or only get yellow are definitely dependent on the actual phrase.  In my case the longest string of available letters was 6 such that I could only get yellow entries with 20 unique letters.   Adding one unique letter still had it all yellow, adding a second unique got me yellow and blue and adding the third unique letter got me all blue.
